# Fly.io configuration for RefactorIQ Backend
app = "refactoriq-backend"
primary_region = "fra"  # Frankfurt (change to your preferred region)

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  ENVIRONMENT = "production"
  LOG_LEVEL = "INFO"
  LOG_FORMAT = "json"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/api/v1/health"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[[mounts]]
  source = "data"
  destination = "/data"

