# Prometheus configuration for RefactorIQ monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'refactoriq-production'
    replica: 'prometheus-01'

# Load alerting rules
rule_files:
  - "alert_rules.yml"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # RefactorIQ Backend Application
  - job_name: 'refactoriq-backend'
    static_configs:
      - targets: ['backend:9090']  # Assuming metrics endpoint on port 9090
    scrape_interval: 15s
    metrics_path: /api/v1/health/metrics
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:8080']
    scrape_interval: 30s
    metrics_path: /nginx-health

  # PostgreSQL metrics using postgres_exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis metrics using redis_exporter  
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Node/System metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Docker container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

  # Application-specific metrics
  - job_name: 'refactoriq-app-metrics'
    static_configs:
      - targets: ['backend:8000']
    scrape_interval: 15s
    metrics_path: /api/v1/metrics
    scheme: http
    honor_labels: true

# Remote write configuration (for long-term storage)
# Uncomment and configure if using external storage like Cortex or Thanos
# remote_write:
#   - url: "https://cortex.example.com/api/prom/push"
#     basic_auth:
#       username: "prometheus"
#       password: "secret"